#! python3
#mapit.py - launches a map in the browser using an address from the clipboard or command line
import webbrowser, sys
if len(sys.argv)>1:
    # Get address from command line
    address = ' '.join(sys.argv[1:])

    #Get address from clipboard
else:
    address = pyperclip.paste()

webbrowser.open('https://www.google.ca/maps/place/' + address)
